// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqdjvMaS0C8v8284SiQqY64lfblK9tUjo',
    appId: '1:339444274332:web:17fa03e33c489152f0c959',
    messagingSenderId: '339444274332',
    projectId: 'gymboobd',
    authDomain: 'gymboobd.firebaseapp.com',
    storageBucket: 'gymboobd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxBYzeazAoddmWrTPsew-ZvM9FyAxiozg',
    appId: '1:339444274332:android:e10a4c4e44397d7bf0c959',
    messagingSenderId: '339444274332',
    projectId: 'gymboobd',
    storageBucket: 'gymboobd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqdjvMaS0C8v8284SiQqY64lfblK9tUjo',
    appId: '1:339444274332:web:4615fa6aed7fb1f6f0c959',
    messagingSenderId: '339444274332',
    projectId: 'gymboobd',
    authDomain: 'gymboobd.firebaseapp.com',
    storageBucket: 'gymboobd.firebasestorage.app',
  );
}
